### ISSUE TITLE
menu with commands

### ISSUE THREAD

**Issue by vladzht1** [miit-projects/miit-guide-bot#11]
## Краткое описание
Необходимо сделать выпадающее меню с подсказками о командах (см. картинку) на `production` боте.

## Примечания
Не закрывать данное issue до тех пор, пока описанный выше функционал не появится на `production` версии бота.

![image](https://user-images.githubusercontent.com/74919692/194778950-836986b1-9154-49d2-93bb-a7aa192ba524.png)

**Comment by mikhailmusic** [comment]
`BotFather` -> `/start` -> `/mybots` -> выбор `username` бота -> `Edit Bot` -> `Edit Commands` -> команда - текст (`Example: start - Начать общение с ботом`). Или ты хочешь это кодом сделать?

**Comment by vladzht1** [comment]
@mikhailmusic, нет, это нужно делать руками через `BotFather`. Эта issue нужна, чтобы закрыть её на релизе, дабы не забыть добавить меню команд в `production` бота.
